dist: trusty
language: generic

services:
  - docker

matrix:
  # Lets build be marked complete if all required matrix is finished
  # https://docs.travis-ci.com/user/build-matrix/#fast-finishing
  fast_finish: true

  include:
  # Docker w/ framework
  - os: linux
    env: TYPE="docker"
    sudo: required

  # Conda w/o mantid-framework
  - os: linux
    env: TYPE="conda" CONDA=2.7    PKG="mantid-total-scattering-python-wrapper"
    sudo: required
  - os: linux
    env: TYPE="conda" CONDA=2.7.14 PKG="mantid-total-scattering-python-wrapper"
    sudo: required
  - os: linux
    env: TYPE="conda" CONDA=3.6    PKG="mantid-total-scattering-python-wrapper"
    sudo: required

  # Conda w/ mantid-framework
  - os: linux
    env: TYPE="conda" CONDA=2.7.14 PKG="mantid-total-scattering"
    sudo: required
  - os: linux
    env: TYPE="conda" CONDA=3.6    PKG="mantid-total-scattering"
    sudo: required

  # Since Mantid Framework is prone to seg faults
  allow_failures:
    - os: linux
      env: TYPE="conda" CONDA=2.7.14 PKG="mantid-total-scattering"
      sudo: required
    - os: linux
      env: TYPE="conda" CONDA=3.6    PKG="mantid-total-scattering"
      sudo: required

before_install:
  - | 
    if [[ "${TYPE}" == "docker" ]]; then
      docker build -t test-env -f .ci/Dockerfile.nightly_ubuntu16.04 .;
      test_cmd=`./.ci/construct_test_command.sh`;
    fi

  - |
    if [[ "${TYPE}" == "conda" ]]; then
      MINICONDA_URL="https://repo.continuum.io/miniconda";
      MINICONDA_FILE="Miniconda${CONDA:0:1}-latest-Linux-x86_64.sh";
      wget "${MINICONDA_URL}/${MINICONDA_FILE}";
      bash ${MINICONDA_FILE} -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    fi


install:
  - |
    if [[ "${TYPE}" == "conda" ]]; then
      conda config --set always_yes yes --set changeps1 no --set anaconda_upload no;
      conda config --add channels conda-forge --add channels mantid --add channels mantid/label/nightly;
      conda update  -q conda;
      conda info -a

      conda create -q -n ${PKG} python=$CONDA flake8 conda-build conda-verify anaconda-client;
      source activate ${PKG}

      # Build recipe and install 
      PKG_PATH="./conda.recipe/${PKG}"
      conda build ${PKG_PATH}
      export PKG_FILE=$(conda build ${PKG_PATH} --output)
      conda install ${PKG_FILE}
      
    fi

script:
  - |
    if [[ "${TYPE}" == "docker" ]]; then
      docker run -t test-env /bin/bash -c "$test_cmd";
      sudo python setup.py install;
    fi

  - |
    if [[ "${TYPE}" == "conda" ]]; then
      if [[ "${CONDA}" == 2.7.14 || "${CONDA}" == '3.6' ]]; then
        conda install -c mantid/label/nightly mantid-framework
        python setup.py test;
      fi
    fi

deploy:

 # Deploy pure-python package to PyPI https://pypi.org/project/mantid-total-scattering/
 - provider: pypi
   user: mcdonnellmt
   skip_cleanup: true
   skip_existing: true
   on:
     tags: true
     branch: master
   password:
     secure: ${PYPI_UPLOAD_TOKEN}

 # Deploy conda package to Anaconda.org https://anaconda.org/marshallmcdonnell/mantid-total-scattering
 - provider: script
   script: cd conda.recipe && chmod +x anaconda_upload.sh && ./anaconda_upload.sh ${PKG_FILE}
   skip_cleanup: true
   skip_existing: true
   on:
     branch: master
     tags: true
     condition: $TYPE = conda
